services:
  sih-atellica-qplus-frontend:
    build:
      context: "."
      dockerfile: "./sih-atellica-qplus-frontend/Dockerfile.dev"
    environment:
      - HOST=0.0.0.0
      - PORT=7005
    ports:
      - "7005:7005"
    depends_on:
      - sih-atellica-qplus-backend
    volumes:
      - ./sih-atellica-qplus-frontend:/usr/src/app
      - sih-atellica-qplus-frontend-node_modules:/usr/src/app/node_modules
      - ./certificates:/usr/src/certificates
    profiles:
      - frontend
      - full
  sih-atellica-qlik-service:
    build:
      context: "."
      dockerfile: "./sih-atellica-qlik-service/Dockerfile.dev"
    environment:
      - DB_HOST=db
      - HOST=0.0.0.0
      - SSL=true
      - PORT=8080
      - GATEWAY_HOST=https://sih-atellica-qplus-backend:3001
      - GATEWAY_PATH=/
    ports:
      - "3001:8080"
    depends_on:
      - db
    volumes:
      - ./sih-atellica-qlik-service:/usr/src/app
      - sih-atellica-qlik-service-node_modules:/usr/src/app/node_modules
  sih-atellica-qplus-backend:
    build:
      context: "."
      dockerfile: "./sih-atellica-qplus-backend/Dockerfile.dev"
    environment:
      - DB_HOST=db
      - HOST=0.0.0.0
      - SSL=true
      - PORT=8080
      - QLIK_SERVICE_HOST=https://sih-atellica-qlik-service
      - QLIK_SERVICE_PORT=8080
      - GATEWAY_HOST=https://sih-atellica-qplus-backend:3002
      - GATEWAY_PATH=/
    ports:
      - "3002:8080"
    depends_on:
      - db
    volumes:
      - ./sih-atellica-qplus-backend:/usr/src/app
      - sih-atellica-qplus-backend-node_modules:/usr/src/app/node_modules
  db:
    image: postgres:12.8
    volumes:
      - "./data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sih_qplus
volumes:
  sih-atellica-qplus-frontend-node_modules:
  sih-atellica-qlik-service-node_modules:
  sih-atellica-qplus-backend-node_modules:
